# Story Uplift Modelling: eXplaining colon cancer survival rate after treatment {#story-uplift-modelling}

*Authors: Aleksandra Łuczak (Warsaw University of Technology), Tymoteusz Makowski (Warsaw University of Technology), Kateryna Shulikova (Warsaw School of Economics)*

*Mentors: Miłosz Dobersztyn (McKinsey), Armin Reinert (McKinsey)*

## Introduction 
We will use data about **Chemotherapy for Stage B/C colon cancer** from `survival` package in R. The documentation can be found [here](https://stat.ethz.ch/R-manual/R-devel/library/survival/html/colon.html), the package can be installed with `install.packages("survival")` command in R console. After the installation dataset can be accessed via `survival::colon` command.

<!--
    TODO: Describe why this problem is important. Indicate the most important literature on the problem. 
    TODO(oryginał): Put a description of the problem here. *Indicate the data source.*
-->


### What is Uplift Modelling?

For classical algorithms in machine learning it is hard to predict causal impact of the event because they are more suited for predicting the results after an action. In some cases, such as a marketing campaign or medical treatment, that causal impact might be extremely important. Due to the possibility of using two training sets (treatment and control groups) by uplift modeling this problem was solved. 

Uplift modeling is one of the techniques or a branch of machine learning that tries to forecast class probability differences between group exposed to some action or therapy and control group (without that action or therapy).

This technique also allows to discover in research those groups of patients for which treatment was most beneficial, so it is commonly used not only in marketing campaigns or medical treatments but also in other customer services.

REFERENCES:

* Uplift modeling with survival data - Szymon Jaroszewicz , Piotr Rzepakowski https://home.ipipan.waw.pl/s.jaroszewicz/pdf/HI_KDD14.pdf
* Uplift modeling for clinical trial data - Maciej Jaśkowski, Szymon Jaroszewicz http://people.cs.pitt.edu/~milos/icml_clinicaldata_2012/Papers/Oral_Jaroszewitz_ICML_Clinical_2012.pdf
* Uplift Modeling for Multiple Treatments with Cost Optimization Zhenyu Zhao, Totte Harinen https://arxiv.org/pdf/1908.05372.pdf
* Linear regression for uplift modeling - Krzysztof Rudaś, Szymon Jaroszewicz https://link.springer.com/article/10.1007/s10618-018-0576-8
* Ensemble methods for uplift modeling, Michał Sołtys, Szymon Jaroszewicz, Piotr Rzepakowski https://www.researchgate.net/publication/282845041_Ensemble_methods_for_uplift_modeling

<!-- TODO:
 - Czym jest uplift modelling?
 - Gdzie go się stosuje?
 - Jakie problemy możemy modelować (survival & leki, marketing & zysk)?
-->


### Dataset Description
We use data from one of the first successful trials of adjuvant chemotherapy for colon cancer. There are two type of treatment:

 - *Levamisole* is a low-toxicity compound previously used to treat worm infestations in animals and its effects on the treatment of colon cancer have been noted; 
 - *5-FluoroUracyl(FU)* is a moderately toxic (as these things go) chemotherapy agent. This is the "strongest" one treatment. 

Both of these medications are given after the cancer excision, it's adjutant chemistry, that means "extra post-operative".

There are two records per person, one for recurrence and one for death. Dataset contains 1858 observations and 16 features which are described below.

<table>
 <thead>
  <tr>
   <th style="text-align:left; width: 20%;"> Variable </th>
   <th style="text-align:left; width: 20%;"> Type </th>
   <th style="text-align:left;"> Description </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> id </td>
   <td style="text-align:left;"> categorical </td>
   <td style="text-align:left;"> An id. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> study </td>
   <td style="text-align:left;"> categorical </td>
   <td style="text-align:left;"> 1 for all patients. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> rx </td>
   <td style="text-align:left;"> categorical </td>
   <td style="text-align:left;"> Treatment: Observation, Levamisole or Levamisole+5-FluoroUracyl. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sex </td>
   <td style="text-align:left;"> categorical </td>
   <td style="text-align:left;"> Patient's sex: Male or Female. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> age </td>
   <td style="text-align:left;"> continuous </td>
   <td style="text-align:left;"> Patient's age in years. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> obstruct </td>
   <td style="text-align:left;"> binary </td>
   <td style="text-align:left;"> Stenosis of the colon by the cancer, which is blockage by the tumor. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> perfor </td>
   <td style="text-align:left;"> binary </td>
   <td style="text-align:left;"> Perforation of colon - a flag whether there was a hole in the colon. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> adhere </td>
   <td style="text-align:left;"> binary </td>
   <td style="text-align:left;"> Adherence to the surrounding organs (e.g. bladder). </td>
  </tr>
  <tr>
   <td style="text-align:left;"> nodes </td>
   <td style="text-align:left;"> continuous </td>
   <td style="text-align:left;"> Number of lymph nodes with detectable cancer i.e. during the operation the lymph nodes that were attacked by the cancer are cut out. For the operation to be successful there should be at least 12 lymph nodes. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> time </td>
   <td style="text-align:left;"> continuous </td>
   <td style="text-align:left;"> Days until event or censoring. The time of receiving the treatment is considered to be time = 0, the time that passed in the variable time is the time until death or relapse from receiving the treatment. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> status </td>
   <td style="text-align:left;"> binary </td>
   <td style="text-align:left;"> Censoring status. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> differ </td>
   <td style="text-align:left;"> categorical </td>
   <td style="text-align:left;"> Differentiation of tumour cell (1=well, 2=moderate, 3=poor). The more the better because it is more like colon cells. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> extent </td>
   <td style="text-align:left;"> categorical </td>
   <td style="text-align:left;"> Extent of local spread, what cells did he reach (1=submucosa, 2=muscle, 3=serosa, 4=contiguous structures). The less the better. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> surg </td>
   <td style="text-align:left;"> categorical </td>
   <td style="text-align:left;"> Time from surgery to registration (0=short, 1=long). </td>
  </tr>
  <tr>
   <td style="text-align:left;"> node4 </td>
   <td style="text-align:left;"> binary </td>
   <td style="text-align:left;"> More than 4 positive lymph nodes. </td>
  </tr>
  <tr>
   <td style="text-align:left;"> etype </td>
   <td style="text-align:left;"> categorical </td>
   <td style="text-align:left;"> Event type: 1=recurrence, 2=death. </td>
  </tr>
</tbody>
</table>


### Ideas
There are many ways to use this data:

- prediction of the patient's life expectancy depending on whether they received  treatment or not,
- prediction whether the treatment is effective or not,
- prediction of the life expectancy depending on the medicine administered.

We have decided to focus on the last mentioned approach.


### Why It's worth?
When a patient learns about the colon cancer disease they usually ask *"How much more time do I have left he has left?"*. And now what? What is the treatment? The doctor may indicate a number of therapies that may be effective, but still be unable to tell how much time there is left or what's the patient's expectancy to live.

The aim of this model is helping to provide more accurate data and answer the patient's question.


## Preprocessing data
We remove columns:

- `id`
- `study`
- `etype`

The dataset has been divided into:

- X - all features (without time and rx),
- y - target variable (time),
- treatment - `rx` variable.

Distribution of the variable `rx` is as shown below. This feature has been categorised.

| Levamisole | Levamisole + 5-FU | Observation |
|:----------:|:-----------------:|:-----------:|
| 620        | 608               | 630         |


## Model 
To predict model we used algorithms from the package [causalml](https://github.com/uber/causalml) in Python 3.
To optimize hyper parameters we used algorithms from the package [hyperopt](https://github.com/hyperopt/hyperopt) also in Python 3.
All notebooks and codes can be found on [GitHub](https://github.com/aleksandramiesiac/UpliftModelling_Iml_team4).

The final model is `XGBTRegressor` with following parameters:

<table style="width: 50%; margin: 15px 25%;">
 <thead>
  <tr>
   <th style="text-align:right;"> Parameter </th>
   <th style="text-align:left;"> Value </th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td style="text-align:right;"> colsample_bytree </td>
   <td style="text-align:left;"> 0.7324146695038634 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> gamma </td>
   <td style="text-align:left;"> 0.8249750889337837 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> learning_rate </td>
   <td style="text-align:left;"> 0.8882649077192536 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> max_depth </td>
   <td style="text-align:left;"> 6 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> min_child_weight </td>
   <td style="text-align:left;"> 0.4152689004191612 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> n_estimators </td>
   <td style="text-align:left;"> 250 </td>
  </tr>
 </tbody>
</table>

This gives as Average Treatment(Lev) Effect 70.49 and Average Treatment(Lev+5-FU) Effect 70.89.


## Explanations
<!--
    TODO:(oryginał):
    > Here, show how XAI techniques can be used to solve the problem.
    > Will dataset specific or instance specific techniques help more?
    >
    > Will XAI be useful before (pre), during (in) or after (post) modeling?
    >
    > What is interesting to learn from the XAI analysis?

     - Jak w ogóle to wyjaśniać skoro np. możemy mieć dwa modele?
     - Wizualizacje dopracować (czytelne wykresy, opisy itp.) [ad 4].
-->


### Dataset Level Explainations
<!--
    TODO: Jaka jest istotność zmiennych?
-->


### Instance Level Explainations
<!--
    TODO: Jakieś "ciekawe" przypadki?
-->


## Summary and conclusions 
<!--
    TODO:(oryginał):
    > Here add the most important conclusions related to the XAI analysis.
    > What did you learn? 
    > Where were the biggest difficulties?
    > What else did you recommend?

     - Jakich informacji XAI nam dostarczyło na temat tego problemu?
     - Jak XAI sprawdza się do wyjaśniania upliftu?
     - Dlaczego było warto to modelować (konkretnie ten dataset) [ad 5].
-->
